#!/bin/bash
#
# Log commit messages as a 'highlight' in RescueTime Premium
#
# To enable this hook:
#
# 1. Place this file in your project's .git/hooks directory and make sure its name is "post-commit".
# 2. Make sure it has executable permissions (chmod +x post-commit)
# 3. All commits will be automatically logged as highlight events.
#

function post_highlight {
    # either use the user supplied RESCUETIME_API_KEY value, or fail with a
    # message
    API_KEY=${RESCUETIME_API_KEY?needs to be set};

    # REQUIRED FIELDS - Today's date and commit message
    MESSAGE=$(git log -1 HEAD --pretty=format:%s)
    DATE_TODAY=$(date +"%Y-%m-%d")

    # OPTIONAL - Label
    LABEL=$(basename $(git rev-parse --show-toplevel) |tr [:upper:] [:lower:]);

    if [[ ${#MESSAGE} -gt 20 ]]; then
        curl -s --data "key=$API_KEY&highlight_date=$DATE_TODAY&description=$MESSAGE&source=$LABEL" https://www.rescuetime.com/anapi/highlights_post
    fi
}

case "${1}" in
    --about )
        echo "Submit a commit highlight to RescueTime"
        ;;
    *)
        post_highlight;
        ;;
esac
